<?php

/**
 * Implementation of hook_user_default_permissions().
 */
function ekb_forum_noderef_user_default_permissions() {
  $permissions = array();

  // Exported permission: edit field__item_key_related
  $permissions['edit field__item_key_related'] = array(
    'name' => 'edit field__item_key_related',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_date
  $permissions['edit field_date'] = array(
    'name' => 'edit field_date',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_dev_link_vid
  $permissions['edit field_dev_link_vid'] = array(
    'name' => 'edit field_dev_link_vid',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_dev_time
  $permissions['edit field_dev_time'] = array(
    'name' => 'edit field_dev_time',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_developer
  $permissions['edit field_developer'] = array(
    'name' => 'edit field_developer',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_feature
  $permissions['edit field_feature'] = array(
    'name' => 'edit field_feature',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_forum_pp
  $permissions['edit field_forum_pp'] = array(
    'name' => 'edit field_forum_pp',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_item_key_source
  $permissions['edit field_item_key_source'] = array(
    'name' => 'edit field_item_key_source',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_kb_alliance_manager
  $permissions['edit field_kb_alliance_manager'] = array(
    'name' => 'edit field_kb_alliance_manager',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_kb_company_information
  $permissions['edit field_kb_company_information'] = array(
    'name' => 'edit field_kb_company_information',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_link
  $permissions['edit field_link'] = array(
    'name' => 'edit field_link',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_link_text
  $permissions['edit field_link_text'] = array(
    'name' => 'edit field_link_text',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_minutes
  $permissions['edit field_minutes'] = array(
    'name' => 'edit field_minutes',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_new_feature
  $permissions['edit field_new_feature'] = array(
    'name' => 'edit field_new_feature',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_partner_logo
  $permissions['edit field_partner_logo'] = array(
    'name' => 'edit field_partner_logo',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_sap_partner_documents
  $permissions['edit field_sap_partner_documents'] = array(
    'name' => 'edit field_sap_partner_documents',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_sap_product_manager
  $permissions['edit field_sap_product_manager'] = array(
    'name' => 'edit field_sap_product_manager',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_sap_related_pages
  $permissions['edit field_sap_related_pages'] = array(
    'name' => 'edit field_sap_related_pages',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_sap_vertical
  $permissions['edit field_sap_vertical'] = array(
    'name' => 'edit field_sap_vertical',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_sap_work_with
  $permissions['edit field_sap_work_with'] = array(
    'name' => 'edit field_sap_work_with',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_sub1
  $permissions['edit field_sub1'] = array(
    'name' => 'edit field_sub1',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_sub_sub_feature
  $permissions['edit field_sub_sub_feature'] = array(
    'name' => 'edit field_sub_sub_feature',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_trainseq
  $permissions['edit field_trainseq'] = array(
    'name' => 'edit field_trainseq',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_video_date
  $permissions['edit field_video_date'] = array(
    'name' => 'edit field_video_date',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_video_description
  $permissions['edit field_video_description'] = array(
    'name' => 'edit field_video_description',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_video_duration
  $permissions['edit field_video_duration'] = array(
    'name' => 'edit field_video_duration',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_video_file_link
  $permissions['edit field_video_file_link'] = array(
    'name' => 'edit field_video_file_link',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_video_password
  $permissions['edit field_video_password'] = array(
    'name' => 'edit field_video_password',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: edit field_video_url
  $permissions['edit field_video_url'] = array(
    'name' => 'edit field_video_url',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: view field__item_key_related
  $permissions['view field__item_key_related'] = array(
    'name' => 'view field__item_key_related',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: view field_date
  $permissions['view field_date'] = array(
    'name' => 'view field_date',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_dev_link_vid
  $permissions['view field_dev_link_vid'] = array(
    'name' => 'view field_dev_link_vid',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_dev_time
  $permissions['view field_dev_time'] = array(
    'name' => 'view field_dev_time',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_developer
  $permissions['view field_developer'] = array(
    'name' => 'view field_developer',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_feature
  $permissions['view field_feature'] = array(
    'name' => 'view field_feature',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_forum_pp
  $permissions['view field_forum_pp'] = array(
    'name' => 'view field_forum_pp',
    'roles' => array(
      '0' => 'Administrator',
    ),
  );

  // Exported permission: view field_item_key_source
  $permissions['view field_item_key_source'] = array(
    'name' => 'view field_item_key_source',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_kb_alliance_manager
  $permissions['view field_kb_alliance_manager'] = array(
    'name' => 'view field_kb_alliance_manager',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_kb_company_information
  $permissions['view field_kb_company_information'] = array(
    'name' => 'view field_kb_company_information',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_link
  $permissions['view field_link'] = array(
    'name' => 'view field_link',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_link_text
  $permissions['view field_link_text'] = array(
    'name' => 'view field_link_text',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_minutes
  $permissions['view field_minutes'] = array(
    'name' => 'view field_minutes',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_new_feature
  $permissions['view field_new_feature'] = array(
    'name' => 'view field_new_feature',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_partner_logo
  $permissions['view field_partner_logo'] = array(
    'name' => 'view field_partner_logo',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_sap_partner_documents
  $permissions['view field_sap_partner_documents'] = array(
    'name' => 'view field_sap_partner_documents',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_sap_product_manager
  $permissions['view field_sap_product_manager'] = array(
    'name' => 'view field_sap_product_manager',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_sap_related_pages
  $permissions['view field_sap_related_pages'] = array(
    'name' => 'view field_sap_related_pages',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_sap_vertical
  $permissions['view field_sap_vertical'] = array(
    'name' => 'view field_sap_vertical',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_sap_work_with
  $permissions['view field_sap_work_with'] = array(
    'name' => 'view field_sap_work_with',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_sub1
  $permissions['view field_sub1'] = array(
    'name' => 'view field_sub1',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_sub_sub_feature
  $permissions['view field_sub_sub_feature'] = array(
    'name' => 'view field_sub_sub_feature',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_trainseq
  $permissions['view field_trainseq'] = array(
    'name' => 'view field_trainseq',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_video_date
  $permissions['view field_video_date'] = array(
    'name' => 'view field_video_date',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_video_description
  $permissions['view field_video_description'] = array(
    'name' => 'view field_video_description',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_video_duration
  $permissions['view field_video_duration'] = array(
    'name' => 'view field_video_duration',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_video_file_link
  $permissions['view field_video_file_link'] = array(
    'name' => 'view field_video_file_link',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_video_password
  $permissions['view field_video_password'] = array(
    'name' => 'view field_video_password',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  // Exported permission: view field_video_url
  $permissions['view field_video_url'] = array(
    'name' => 'view field_video_url',
    'roles' => array(
      '0' => 'Administrator',
      '1' => 'General Role',
    ),
  );

  return $permissions;
}
